spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://root:password@mongodb:27017/fitnessactivity?authSource=admin
      database: fitnessactivity
    rabbitmq:
      host: rabbitmq
      port: 5672
      username: rabbit
      password: rabbitpass

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

rabbitmq:
  exchange:
    name: activity.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

server:
  port: 8082
