spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://root:password@mongodb:27017/fitnessrecommendation?authSource=admin
      database: fitnessrecommendation
    rabbitmq:
      host: rabbitmq
      port: 5672
      username: rabbit
      password: rabbitpass

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

rabbitmq:
  exchange:
    name: ai.exchange
  queue:
    name: ai.queue
  routing:
    key: ai.tracking

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

server:
  port: 8083
