spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://postgres:5432/fitness_user_db
    username: postgres
    password: 1210
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 8081
